baseURL = "https://tejas.wtf/"
languageCode = "en-us"
title = "Tejas Siripurapu"
theme = "archie"
copyright = "© Athul"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
	mode="light" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Writing from a [Coder](https://github.com/teejas)"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/teejas"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/tejas-siripurapu-7b7b81105/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ojsimpsome/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/tejas.siripurapu/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Notebooks"
url = "/notebooks"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
